title: Mitchell Rath # your name (or website title) here
logo: "images/Headshot_Github.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a health data scientist by training, with an academic background in genetic biology and biostatistics. I am currently pursuing a Master's degree in Data Science and Analytics with the University of Calgary, due to graduate in 2021.<br>
  I have been developing a career in healthcare research, combining my undergraduate and graduate training in a research position conducting data analysis & research coordination in a pediatric clinical setting. <br> 
  <br>
  <a href="https://www.researchgate.net/profile/Mitchell_Rath2">View My ResearchGate Profile</a> <br>
  <a href="https://www.linkedin.com/in/mitchell-rath-210844183">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
