title: Mitchell Rath # your name (or website title) here
logo: "/images/Headshot.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Thank you for visiting the portfolio of Mitchell Rath.
  <br><br>
  I am a health data scientist by training, with a background in genetic biology, statistics and endocrinology. <br> 
  Included in this page is some select projects I have worked on through the Health Data Science and Biostatistics Graduate Program the the University of Calgary.
  <br><br>
  <a href="https://www.researchgate.net/profile/Mitchell_Rath2">View My ResearchGate Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/mitchell-rath-210844183">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
